### ISSUE TITLE
[Bug] Selling Drugs

### ISSUE THREAD

**Issue by GM-galibmahin** [cadburry6969/cad-drugsales#10]
Sometime when you sell the drugs some peds dont accept neither rejects. So it happens a lot, and cant sell the drugs

**Comment by cadburry6969** [comment]
are you using old qbcore?

**Comment by MadManDanCat** [comment]
@galibmahin replace this function



 local function InitiateSell(ped, randamt)
    local AlreadySold = false
    local k = CurrentZone.name
    randamt = randamt or 1 -- Set the default value for randamt if it's not provided

    if Config.ZoneDrugs[k] then
        local player = QBCore.Functions.GetPlayerData()
        local playerInventory = player.items

        for _, randdrug in ipairs(Config.ZoneDrugs[k]) do
            local price = randdrug.price
            local item = QBCore.Shared.Items[randdrug.item]
            local itemData = nil

            for _, inventoryItem in ipairs(playerInventory) do
                if inventoryItem.name == randdrug.item then
                    itemData = inventoryItem
                    break
                end
            end

            if not AlreadySold then
                if itemData and itemData.amount >= randamt then
                    AlreadySold = true
                    InitiateSellProgress = true
                    local SaleMenu = {
                        {
                            header = tostring(randamt).."x of "..QBCore.Shared.Items[tostring(randdrug.item)]['label'].." for "..QBCore.Shared.Round(randamt * price, 0).."$",
                            isMenuHeader = true
                        },
                        {
                            header = "Accept Offer",
                            params = {
                                event = 'cad-drugsales:salesinitiate',
                                args = {
                                    type = 'buy',
                                    item = randdrug.item,
                                    price = price,
                                    amt = randamt,
                                    tped = ped
                                }
                            }
                        },
                        {
                            header = "Decline Offer",
                            params = {
                                event = 'cad-drugsales:salesinitiate',
                                args = {
                                    type = 'close',
                                    tped = ped
                                }
                            }
                        }
                    }
                    exports[Config.Menu]:openMenu(SaleMenu)
                    TimeoutMenu(ped)
                    break
                else
                    if Config.Debug then
                        print("You don't have enough ["..randdrug.item.."] to sell")
                        if itemData then
                            print("You have ["..itemData.amount.."] but need ["..randamt.."]")
                        else
                            print("You have [0] but need ["..randamt.."]")
                        end
                    end
                end
            end
        end
        if not AlreadySold then
            SetPedAsNoLongerNeeded(ped)
            TriggerEvent('QBCore:Notify', 'Person wanted more stuff but you didn\'t have!')
        end
    end
end

**Comment by cadburry6969** [comment]
@MadManDanCat & @galibmahin 
Pushed [Version 2.1.2](https://github.com/cadburry6969/cad-drugsales/releases/tag/v2.1.2) which should be a permanent fix to these
