### ISSUE TITLE
"Talk" and nothing happen.

### ISSUE THREAD

**Issue by SteffenFriis** [cadburry6969/cad-drugsales#11]
Sometimes (actually quite often) when you "talk" with NPC's they don't do anything.. They don't call cops, they do not say if they want to buy and they just stand there and look at you. 

If I try to "talk" again, it just informs me I've spoken with this ped already. 

It started coming after the newest version.

**Comment by cadburry6969** [comment]
Not sure what inventory are you using also post screenshots for errors if any

**Comment by SteffenFriis** [comment]
No errors in live console or F8. 

Using the Lj-inventory, but the older version works fine.. Hmm

**Comment by cadburry6969** [comment]
Restart your server and try 
Also dont restart the script when you are in.
Let me know once you have done this
