### ISSUE TITLE
Dublicated sell drugs options

### ISSUE THREAD

**Issue by Stevekunkku** [cadburry6969/cad-drugsales#12]
When I look at someone they sometime have more then 1 selling option

(I Have tranlated the options so the "myy huumeita" is selling option)
![image](https://github.com/cadburry6969/cad-drugsales/assets/141387283/81e94f49-f688-4b67-9ad8-87344c9902eb)

**Comment by cadburry6969** [comment]
Is that ox_target I dont think I have added support for ox_target anyways I'm going to remake the whole drug sales for qb/esx and ox

**Comment by Stevekunkku** [comment]
Okey thanks I wait or try to figure it out
