### ISSUE TITLE
Script Error on sale

### ISSUE THREAD

**Issue by Arkosee** [cadburry6969/cad-drugsales#13]
Getting this error on install and trying to sell a drug within a zone

![FiveM_b2802_GTAProcess_yKe1yYMyTY](https://github.com/cadburry6969/cad-drugsales/assets/105973488/ea4784cb-b506-4739-8227-6ec6d214ccb1)

**Comment by cadburry6969** [comment]
- What inventory do you use?
- Have you changed anything in the config?
- Do you have the items in the inventory mentioned in the config?

**Comment by Arkosee** [comment]
- ox_inventory
- Just the zone size and drugs (converted to have a single square box covering the entire island so drugs can be sold anywhere + added a weed bag)
- Yes

**Comment by cadburry6969** [comment]
can you add `print(randamt, maxamt)` in line 131 after `if maxamt ~= 0 then` and post the ss of the result here

**Comment by Arkosee** [comment]
![Screenshot 2023-09-29 211814](https://github.com/cadburry6969/cad-drugsales/assets/105973488/4475df23-391d-4d03-9e1e-ae239b626170)

**Comment by Arkosee** [comment]
Okay figured it out, now we have a different issue... Now they won't remove the item upon successful sale xD but they give money for it even though it doesn't get removed

**Comment by cadburry6969** [comment]
https://github.com/cadburry6969/cad-drugsales/commit/7b9bc0624c09e0e5ed6dbd7f131ae87819f44e08

can you check this commit

**Comment by Arkosee** [comment]
This fixed the issue :)
