### ISSUE TITLE
initiateSell Issue

### ISSUE THREAD

**Issue by G1Gi** [cadburry6969/cad-drugsales#16]
You loop though the #items in initiateSell function although still selects a random item in the #items rather than using the current interval

Current:
local data = items[math.random(1, #items)]

Should be:
local data = items[i]

Small issue but my experience it pops up with "Person was interested to buy, but you dint have enough to sell!" like 3/10 times

**Comment by cadburry6969** [comment]
Good observation, I'll fix it when I'm on my pc or else you can make a pr.

**Comment by cadburry6969** [comment]
https://github.com/cadburry6969/cad-drugsales/commit/02346321156a40d65b69af4e88e88cb23df2d491

should be fine now
