### ISSUE TITLE
For put more drugs not sell

### ISSUE THREAD

**Issue by on4sat** [cadburry6969/cad-drugsales#2]
Possible put more drugs!!  for exemple for meth and coke if possible put that on exemple in script
Regards

**Comment by HATE-dev** [comment]
cant add more locations it messes up the script

**Comment by tcantrell** [comment]
yes you can add more locations, add them to the shared.lua. You need to add poly zones, and which drug/item you want to sell in that zone.  After adding more zones etc, you are right Hate-Dev it does not function properly. The newest zone works, but not the original baller zone. Also to add when you do not have the item to sell, the notification of "if Config.Debug then print('You dont have ['..v.item..'] to sell') end" does not notify.

**Comment by cadburry6969** [comment]
Please go through the readme thoroughly.

**Comment by HATE-dev** [comment]
![image](https://user-images.githubusercontent.com/78761393/169693167-9e87299a-e88d-45b4-a7bd-6c7997b1efc6.png)
![image](https://user-images.githubusercontent.com/78761393/169693187-a2cf2e99-2c84-427f-87af-b5301c4ddf26.png)
![image](https://user-images.githubusercontent.com/78761393/169693191-1a40f3a2-9ea7-4f43-ba24-34343a467926.png)
not working
