### ISSUE TITLE
adding new locations

### ISSUE THREAD

**Issue by HATE-dev** [cadburry6969/cad-drugsales#3]
![image](https://user-images.githubusercontent.com/78761393/169693167-9e87299a-e88d-45b4-a7bd-6c7997b1efc6.png)
![image](https://user-images.githubusercontent.com/78761393/169693187-a2cf2e99-2c84-427f-87af-b5301c4ddf26.png)
![image](https://user-images.githubusercontent.com/78761393/169693191-1a40f3a2-9ea7-4f43-ba24-34343a467926.png)
not working

**Comment by realSixGrams** [comment]
Look at the 'star' Road, it has a vector missing a "2"
