### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by shadowTW** [cadburry6969/cad-drugsales#4]
![image](https://user-images.githubusercontent.com/64441627/169706653-e3dd0843-3c6d-46d7-8a74-e46d801137ff.png)

**Comment by realSixGrams** [comment]
I am getting this as well, but I will try and solve it on my own - I am not that good at this kinda thing though.

**Comment by cadburry6969** [comment]
will push an update soon with fix

**Comment by cadburry6969** [comment]
Please check the latest version
