### ISSUE TITLE
You cannot target other peds outside of the zones you create. 

### ISSUE THREAD

**Issue by Kolvicht** [cadburry6969/cad-drugsales#5]

**Comment by Kolvicht** [comment]
Sorry, clicked enter to quick. 

But, when I target a ped outside of the zones created, it throws this error back at me.

Updated everything, target, core, and this resource.

https://i.imgur.com/tPDBcRv.png

**Comment by cadburry6969** [comment]
will push and update soon with fix

**Comment by cadburry6969** [comment]
Please check v2.0.6 update
