### ISSUE TITLE
qb-shop compatibility problem

### ISSUE THREAD

**Issue by MvtiasG** [cadburry6969/cad-drugsales#7]
Hi, I am having a serious problem with this script, I can't use it in conjunction with qb-shops. Because if I use this script the stores that use qb-target do not respond to me, they just stop working. Is there any solution for this error ?

**Comment by cadburry6969** [comment]
Please go through the code once, I have given a blacklist ped option just add the peds which are in the shop to that config, and also there is an export which can allow/disallow the target to show on ped even if in zone
